version: '2.1'
orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
  
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - aws-ecr/build-and-push-image:
          repo: nanophate-cci-intervals
          registry-id: 365228465016
          region: ap-northeast-1
